### ISSUE TITLE
Windows 10 issues

### ISSUE THREAD

**Issue by andrew-goetz-com** [Wandang/TwitchPlaysAutoChess#7]
No commands work for me. I see mouse movements but it is not correct in windows 10 environment @ 1920x1080. Also commands such as !write do not function.

**Comment by Wandang** [comment]
Is there any log output or the program crashing?

**Comment by Wandang** [comment]
pynput has dozens of problems with keyboard [input on windows](https://github.com/moses-palmer/pynput/issues)

To fix this I temporarily re-implemented every keyboard action to be done via mouseinput. Writing to allchat or having a promotional shoutout is therefore not possible anymore.
